
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { CustomDatabase } from './types.d';

const SUPABASE_URL = "https://xaltintlvsmmpgapczlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbHRpbnRsdnNtbXBnYXBjemxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5Njk3MTEsImV4cCI6MjA1ODU0NTcxMX0.sxYIkGTWU2NgqZN0a4yGD5J0tNByQwWyTaqmJ0MGBjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
